
INDIR		?= OrthoFinder_diamond/Blast_results/OrthoFinder/Results_Aug19/Orthogroup_Sequences


seqs		:= $(wildcard ${INDIR}/*.fa)
aln		:= $(seqs:.fa=.fasaln)

align:	$(aln)

%.fasaln : %.fa
	mafft --auto $< > $@
